/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicios.uri1012;

/**
 * 
 * @author Eduardo Jose Gautier
 * 
 */

public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
